In [1]:
import numpy as np
from dateutil.parser import parse

导入数据

In [2]:
# 不需要的行需要skip掉
# 默认没有分隔符，所以需要指定delimiter
# 不加载全部的情况下需要指定加载哪些列usecols
# 希望把每一列加载到单独的数组中需要设置unpack=True，并指定对应的变量名，列举下有unpack和没有的区别
stock_info = np.loadtxt(r'E:\项目\BABA_stock.csv',delimiter=',', usecols=(1, 2, 3, 4, 5), skiprows=1, unpack=True)


理解数据

In [3]:
stock_info.shape

(5, 755)

In [4]:
stock_info

array([[1.830700e+02, 1.889100e+02, 1.849800e+02, ..., 7.946000e+01,
        7.901000e+01, 7.897000e+01],
       [1.461019e+07, 1.256109e+07, 8.848863e+06, ..., 1.472746e+07,
        7.761672e+06, 1.169603e+07],
       [1.880600e+02, 1.877100e+02, 1.851500e+02, ..., 7.920000e+01,
        7.852000e+01, 7.945000e+01],
       [1.881700e+02, 1.897900e+02, 1.860600e+02, ..., 8.048000e+01,
        7.912000e+01, 7.975000e+01],
       [1.825600e+02, 1.871400e+02, 1.837500e+02, ..., 7.847000e+01,
        7.771000e+01, 7.846000e+01]])

倒序排列

In [5]:
stock_info = stock_info[:, ::-1]
stock_info

array([[7.897000e+01, 7.901000e+01, 7.946000e+01, ..., 1.849800e+02,
        1.889100e+02, 1.830700e+02],
       [1.169603e+07, 7.761672e+06, 1.472746e+07, ..., 8.848863e+06,
        1.256109e+07, 1.461019e+07],
       [7.945000e+01, 7.852000e+01, 7.920000e+01, ..., 1.851500e+02,
        1.877100e+02, 1.880600e+02],
       [7.975000e+01, 7.912000e+01, 8.048000e+01, ..., 1.860600e+02,
        1.897900e+02, 1.881700e+02],
       [7.846000e+01, 7.771000e+01, 7.847000e+01, ..., 1.837500e+02,
        1.871400e+02, 1.825600e+02]])

上涨下跌的天数

In [6]:
close_info = stock_info[0]
open_info = stock_info[2]
# 闭市时的价格
close_info

array([ 78.97,  79.01,  79.46,  81.21,  80.78,  79.89,  78.84,  78.61,
        77.65,  76.4 ,  76.94,  76.61,  75.91,  75.82,  78.83,  79.2 ,
        79.41,  79.72,  79.8 ,  79.16,  77.16,  79.29,  79.35,  79.03,
        78.32,  78.79,  79.  ,  81.12,  75.59,  78.35,  80.97,  82.  ,
        76.69,  77.3 ,  76.62,  78.06,  77.84,  77.64,  77.56,  75.92,
        75.45,  77.77,  78.39,  78.27,  77.  ,  78.15,  78.62,  78.73,
        79.14,  76.29,  74.23,  76.28,  78.04,  79.53,  79.65,  78.97,
        78.64,  79.35,  78.99,  81.46,  81.74,  80.57,  81.74,  81.25,
        82.65,  82.77,  84.42,  84.18,  84.49,  83.19,  83.59,  83.1 ,
        83.12,  82.48,  84.34,  83.8 ,  83.67,  84.75,  84.59,  85.  ,
        85.24,  87.33,  91.77,  98.25,  97.17,  96.66,  97.  ,  97.  ,
        96.86,  95.65,  95.79,  93.88,  93.94,  95.06,  94.88,  96.  ,
        97.19,  97.42,  99.25, 103.78, 102.32, 102.57,  99.62, 100.8 ,
       100.28, 102.4 , 104.45, 104.64, 103.03, 101.45, 106.  , 109.36,
      

In [7]:
# 开市时的价格
open_info

array([ 79.45 ,  78.52 ,  79.2  ,  79.   ,  81.08 ,  80.12 ,  79.8  ,
        78.85 ,  78.3  ,  77.65 ,  76.81 ,  76.89 ,  75.96 ,  75.64 ,
        79.52 ,  78.35 ,  78.94 ,  79.79 ,  79.43 ,  80.01 ,  78.825,
        77.86 ,  79.83 ,  78.71 ,  78.65 ,  79.07 ,  78.95 ,  79.17 ,
        78.53 ,  76.99 ,  78.49 ,  81.   ,  79.15 ,  76.65 ,  77.24 ,
        77.11 ,  78.19 ,  78.   ,  77.39 ,  76.43 ,  75.25 ,  76.89 ,
        78.31 ,  77.84 ,  78.45 ,  77.9  ,  78.75 ,  79.04 ,  79.16 ,
        76.83 ,  75.8  ,  75.5  ,  76.98 ,  78.31 ,  79.12 ,  79.04 ,
        78.47 ,  79.   ,  78.44 ,  79.33 ,  81.79 ,  81.83 ,  81.18 ,
        81.78 ,  80.6  ,  82.48 ,  83.27 ,  84.71 ,  84.   ,  84.47 ,
        82.86 ,  83.6  ,  83.46 ,  83.37 ,  82.79 ,  84.34 ,  83.3  ,
        83.75 ,  85.01 ,  84.99 ,  85.05 ,  86.01 ,  92.14 ,  92.98 ,
        98.28 ,  96.15 ,  96.17 ,  97.25 ,  96.91 ,  96.47 ,  95.59 ,
        95.68 ,  93.75 ,  94.15 ,  94.6  ,  95.35 ,  96.14 ,  97.3  ,
        97.97 , 100.

上涨天数

In [8]:
rise_count = len(close_info[open_info - close_info > 0])
print('rise count:' + str(rise_count))

rise count:395


下跌天数

In [9]:
fall_count = len(close_info[open_info - close_info <=0])
print('fail count:' + str(fall_count))

fail count:360


In [10]:
# 上涨天数占比
rise_count / close_info.size

0.5231788079470199

In [11]:
# 日线转换为周线
high_info = stock_info[3]
low_info = stock_info[4]

In [12]:
# loadtxt方法有一个converters参数, 可以利用自定义的函数把string做转换
def convert_date(d):
    return  parse(d).weekday()
stock_info = np.loadtxt(r'E:\项目\BABA_stock.csv', delimiter=',',
                       usecols=(0, 1, 2, 3, 4, 5),skiprows=1, dtype='S', converters={0:convert_date})

In [13]:
print(stock_info)

[[b'0' b'183.0700' b'14610190.0000' b'188.0600' b'188.1700' b'182.5600']
 [b'4' b'188.9100' b'12561090.0000' b'187.7100' b'189.7900' b'187.1400']
 [b'3' b'184.9800' b'8848863.0000' b'185.1500' b'186.0600' b'183.7500']
 ...
 [b'1' b'79.4600' b'14727460.0000' b'79.2000' b'80.4800' b'78.4700']
 [b'0' b'79.0100' b'7761672.0000' b'78.5200' b'79.1200' b'77.7100']
 [b'4' b'78.9700' b'11696030.0000' b'79.4500' b'79.7500' b'78.4600']]


In [14]:
# 倒序排列
stock_info = stock_info[::-1, :].astype('f8')
# 需要按照每周分组
# 先找到周一的数据的索引
week_split = np.where(stock_info[:, 0] == 0)[0]
# 按照周一去分组, split返回给定索引的分组
# 可以指定任意间隔的索引, 所以split以一个list的形式返回
week_infos_temp = np.split(stock_info, week_split)
print(type(week_infos_temp))

<class 'list'>


In [15]:
# 为了简单起见, 我们这里只使用周一数据有五天的
week_infos_temp

[array([[4.000000e+00, 7.897000e+01, 1.169603e+07, 7.945000e+01,
         7.975000e+01, 7.846000e+01]]),
 array([[0.000000e+00, 7.901000e+01, 7.761672e+06, 7.852000e+01,
         7.912000e+01, 7.771000e+01],
        [1.000000e+00, 7.946000e+01, 1.472746e+07, 7.920000e+01,
         8.048000e+01, 7.847000e+01],
        [2.000000e+00, 8.121000e+01, 1.490092e+07, 7.900000e+01,
         8.173500e+01, 7.899000e+01],
        [3.000000e+00, 8.078000e+01, 8.812676e+06, 8.108000e+01,
         8.178000e+01, 8.020000e+01],
        [4.000000e+00, 7.989000e+01, 8.628875e+06, 8.012000e+01,
         8.589000e+01, 7.915500e+01]]),
 array([[0.000000e+00, 7.884000e+01, 9.184890e+06, 7.980000e+01,
         7.984000e+01, 7.868000e+01],
        [1.000000e+00, 7.861000e+01, 9.576697e+06, 7.885000e+01,
         7.956000e+01, 7.780010e+01],
        [2.000000e+00, 7.765000e+01, 1.145640e+07, 7.830000e+01,
         7.862000e+01, 7.657000e+01],
        [3.000000e+00, 7.640000e+01, 9.948096e+06, 7.765000e+01,
    

In [16]:
week_info = [x for x in week_infos_temp if len(x) == 5]
# 每个星期的数据都是一样的了, 我们在把他转换成ndarray
w = np.array(week_info)
print(w.shape)
print(w[:3])
week_open = w[:, 0, 3]
print(week_open[:3])
week_close = w[:, -1,1]
print(week_close[:3])
week_high = w[:, :, 3].max(axis=1)
print(week_high[:3])

(114, 5, 6)
[[[0.000000e+00 7.901000e+01 7.761672e+06 7.852000e+01 7.912000e+01
   7.771000e+01]
  [1.000000e+00 7.946000e+01 1.472746e+07 7.920000e+01 8.048000e+01
   7.847000e+01]
  [2.000000e+00 8.121000e+01 1.490092e+07 7.900000e+01 8.173500e+01
   7.899000e+01]
  [3.000000e+00 8.078000e+01 8.812676e+06 8.108000e+01 8.178000e+01
   8.020000e+01]
  [4.000000e+00 7.989000e+01 8.628875e+06 8.012000e+01 8.589000e+01
   7.915500e+01]]

 [[0.000000e+00 7.884000e+01 9.184890e+06 7.980000e+01 7.984000e+01
   7.868000e+01]
  [1.000000e+00 7.861000e+01 9.576697e+06 7.885000e+01 7.956000e+01
   7.780010e+01]
  [2.000000e+00 7.765000e+01 1.145640e+07 7.830000e+01 7.862000e+01
   7.657000e+01]
  [3.000000e+00 7.640000e+01 9.948096e+06 7.765000e+01 7.790000e+01
   7.609000e+01]
  [4.000000e+00 7.694000e+01 1.009680e+07 7.681000e+01 7.728000e+01
   7.566000e+01]]

 [[0.000000e+00 7.661000e+01 7.715004e+06 7.689000e+01 7.700000e+01
   7.594000e+01]
  [1.000000e+00 7.591000e+01 8.008683e+06 7.59600

In [17]:
week_low = w[:, :, 4].min(axis=1)
print(week_low[:3])

[79.12 77.28 75.91]


In [18]:
w_info = np.array([week_open, week_close, week_high, week_close])
print('result:', w_info.T)

result: [[ 78.52   79.89   81.08   79.89 ]
 [ 79.8    76.94   79.8    76.94 ]
 [ 76.89   79.2    79.52   79.2  ]
 [ 78.94   77.16   80.01   77.16 ]
 [ 77.86   78.79   79.83   78.79 ]
 [ 77.11   75.92   78.19   75.92 ]
 [ 75.25   77.     78.45   77.   ]
 [ 77.9    76.29   79.16   76.29 ]
 [ 79.33   81.25   81.83   81.25 ]
 [ 80.6    84.49   84.71   84.49 ]
 [ 84.47   82.48   84.47   82.48 ]
 [ 82.79   84.59   85.01   84.59 ]
 [ 84.99   98.25   92.98   98.25 ]
 [ 98.28   96.86   98.28   96.86 ]
 [ 96.47   95.06   96.47   95.06 ]
 [ 97.38  104.64  104.    104.64 ]
 [105.16  107.71  108.25  107.71 ]
 [106.52  105.79  108.44  105.79 ]
 [105.45  106.    107.3   106.   ]
 [106.79  101.85  107.89  101.85 ]
 [101.5   103.94  104.47  103.94 ]
 [104.98  101.93  104.98  101.93 ]
 [102.65   97.57  103.85   97.57 ]
 [100.07   92.99  100.07   92.99 ]
 [ 92.451  93.39   94.85   93.39 ]
 [ 93.02   90.48   95.28   90.48 ]
 [ 90.05   93.28   92.51   93.28 ]
 [ 92.05   88.67   92.8    88.67 ]
 [ 96.48  10

In [21]:
np.savetxt(r'E:\8期\1.视频\9.项目实战\课件\项目\week_info_baba.csv', w_info.T, 
           header='open, close, high, low', delimiter=',', fmt='%.2f')

# 股票买卖策略评估

策略: 股价超过10日均线买入, 跌破10日均线卖出   
策略二:10日线上穿60日线买入, 下穿60日线卖出

In [22]:
# 加载数据, 把date这一列设置为索引, 简单起见, 只用收盘价进行分析
import numpy as np
import pandas as pd

In [23]:
df = pd.read_csv(r'E:\项目\BABA_stock.csv',index_col='date', 
                usecols=[0,1])
df.head()

close
date                
'2019/04/15'  183.07
'2019/04/12'  188.91
'2019/04/11'  184.98
'2019/04/10'  186.19
'2019/04/09'  187.19

In [24]:
# 将索引转换为datetime形式
df.index = pd.DatetimeIndex(df.index.str.strip("''"))
df.index

DatetimeIndex(['2019-04-15', '2019-04-12', '2019-04-11', '2019-04-10',
               '2019-04-09', '2019-04-08', '2019-04-05', '2019-04-04',
               '2019-04-03', '2019-04-02',
               ...
               '2016-04-28', '2016-04-27', '2016-04-26', '2016-04-25',
               '2016-04-22', '2016-04-21', '2016-04-20', '2016-04-19',
               '2016-04-18', '2016-04-15'],
              dtype='datetime64[ns]', name='date', length=755, freq=None)

In [25]:
# 数据中最近的日期排在前面, 按照日期重新排序
df.sort_index(inplace=True)
print(df.head())
df.describe()

            close
date             
2016-04-15  78.97
2016-04-18  79.01
2016-04-19  79.46
2016-04-20  81.21
2016-04-21  80.78


close
count  755.000000
mean   143.366954
std     40.345464
min     74.230000
25%    102.925000
50%    152.110000
75%    179.155000
max    210.860000

In [26]:
# 策略一: 股价超出10日均线买入, 跌破10日均线卖出
# 先计算10均线数据
ma10 = df.rolling(10).mean().dropna()
# 买点
ma10_model = df['close'] - ma10['close']> 0
ma10_model

date
2016-04-15    False
2016-04-18    False
2016-04-19    False
2016-04-20    False
2016-04-21    False
              ...  
2019-04-09     True
2019-04-10     True
2019-04-11     True
2019-04-12     True
2019-04-15    False
Name: close, Length: 755, dtype: bool

In [27]:
# 第一个值False, 第二个值是True, 在True的时候买入, 需要自定义一个移动窗口处理函数
# 因为卖的时候还需要定义类似的函数, 所以在这里就把两个函数放到一起
# 可以在自定义函数中print一些信息, 例如w值,以方便调试  ----- 这也是调试的一种方式
def get_deal_date(w, is_buy=True):
    if is_buy == True:
        return True if w[0] == False and w[1] == True else False
    else:
        return True if w[0] == True and w[1] == False else False
    

In [28]:
# raw= False 没有的话会有警告信息
# 如果删除NA值,会有缺失, 所以这里用0 填充, 转换bool值方便后面取值
se_buy = ma10_model.rolling(2).apply(get_deal_date, raw=False, args=[False]).fillna(0).astype('bool')
se_sale = ma10_model.rolling(2).apply(get_deal_date, raw=False, args=[False]).fillna(0).astype('bool')
# 具体的买卖点
buy_info = df[se_buy.values]
sale_info = df[se_sale.values]
print(buy_info.head())
print(sale_info.head())

            close
date             
2016-05-13  77.16
2016-05-18  79.03
2016-05-25  75.59
2016-06-01  76.69
2016-06-17  77.00
            close
date             
2016-05-13  77.16
2016-05-18  79.03
2016-05-25  75.59
2016-06-01  76.69
2016-06-17  77.00


In [29]:
# 买和卖的索引值不一样, 不过数据都有63条, 所以删除时间索引信息
no_index_buy_info = buy_info.reset_index(drop=True)
no_index_sale_info = sale_info.reset_index(drop= True)
print(no_index_buy_info.head())
print(no_index_sale_info.head())

   close
0  77.16
1  79.03
2  75.59
3  76.69
4  77.00
   close
0  77.16
1  79.03
2  75.59
3  76.69
4  77.00


In [30]:
# 每次交易的盈利情况
profit = no_index_sale_info - no_index_buy_info
print(profit)
# 大体数据
profit.describe()

    close
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
..    ...
58    0.0
59    0.0
60    0.0
61    0.0
62    0.0

[63 rows x 1 columns]


close
count   63.0
mean     0.0
std      0.0
min      0.0
25%      0.0
50%      0.0
75%      0.0
max      0.0

In [31]:
profit.sum()

close    0.0
dtype: float64

In [32]:
# 总利润是36.07, 注意这是每次买和卖一股的利润(买固定的股数),三年的时间交易了63次
#最多投入210.86,平均投入143.3666954, 按最高投入算利润率(36.07/210.86),年化差不多5%, 按平均投入算0.2515,年化将近8%,当然还有手续费没有算

In [33]:
# 假如有1w美元，最终盈利多少
all_money = 10000
remain = all_money
for i in range(len(no_index_buy_info)):
    buy_count = remain / no_index_buy_info.iloc[i]
    remain = buy_count * no_index_sale_info.iloc[i]
    print(remain)
    


close    10000.0
Name: 0, dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64

In [34]:
# 如果加上每次交易金额的万分之三手续费
all_money = 10000
remain = all_money

fee = 0.0003
for i in range(len(no_index_buy_info)):
    buy_count = remain / no_index_buy_info.iloc[i]
    remain = buy_count * no_index_sale_info.iloc[i]
    print(remain)

close    10000.0
Name: 0, dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64
close    10000.0
dtype: float64

In [35]:
# 将10日线改成60日线试试
# 考虑一种边界情况，买了之后卖点到现在还没有出现（因为先买的，所以不可能买点比卖点多）
# 这种情况我们把当前的股价加到卖点数据中（也可以把买点数据删除）
print(len(no_index_buy_info))
print(len(no_index_sale_info))
if (len(no_index_buy_info) > len(no_index_sale_info)):
    no_index_sale_info.loc[len(no_index_sale_info)] = [df.iloc[-1, 0]]

63
63
